# Generated by Django 4.1.6 on 2023-02-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_news_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categoty',
            new_name='category',
        ),
    ]
