# Generated by Django 4.1.6 on 2023-02-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
