# Generated by Django 4.1.6 on 2023-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='IT', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
